name: survey_kit
description: Create beautiful surveys with Flutter (inspired by iOS ResearchKit Surveys)
version: 0.1.0
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_platform_widgets: ^1.9.0
  go_router: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  lottie: ^1.0.1
  provider: ^6.0.2
  uuid: ^3.0.4
  video_player: ^2.1.6

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/fancy_checkmark.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
