name: survey_kit_image_answer
description: Image Answer View for survey_kit
version: 0.0.1
homepage: https://quickbirdstudios.com
repository: https://github.com/quickbirdstudios/survey_kit
issue_tracker: https://github.com/quickbirdstudios/survey_kit/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  camera: ^0.11.0+1
  image_picker: ^1.0.4
  json_annotation: ^4.0.1
  survey_kit: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true